services:
  ##########################
  # docker-compose-hub.yml #
  ##########################
  piveau-hub-repo:
    image: piveau/hub-repo:3.4.0
    container_name: piveau-hub-repo
    logging:
      options:
        max-size: "50m"
    ports:
      - 8081:8080
      - 8085:8085
      - 5002:5000
    environment:
      - OTEL_SDK_DISABLED=false
      - OTEL_SERVICE_NAME=piveau-hub-repo
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
      - PIVEAU_FEATURE_FLAGS=${PIVEAU_FEATURE_FLAGS}
      - PIVEAU_PROFILE=${PIVEAU_PROFILE}
      - PIVEAU_HUB_BASE_URI=https://opendata.swiss/
      - PIVEAU_HUB_SEARCH_SERVICE=${PIVEAU_HUB_SEARCH_SERVICE}
      - PIVEAU_HUB_API_KEY=${PIVEAU_HUB_API_KEY}
      - PIVEAU_HUB_SHELL_CONFIG={"http":{},"telnet":{}}
      - PIVEAU_TRIPLESTORE_CONFIG={"address":"http://mitmproxy:8888/repositories", "queryEndpoint":"/piveau", "queryAuthEndpoint":"/piveau/statements", "graphEndpoint":"/piveau/rdf-graphs/service", "graphAuthEndpoint":"/piveau/rdf-graphs/service"}
      - PIVEAU_HUB_AUTHORIZATION_PROCESS_DATA=${PIVEAU_HUB_AUTHORIZATION_PROCESS_DATA}
      - JAVA_OPTS=-Xms1g -Xmx2g
    volumes:
      - ./piveau_profile:/piv-profile:ro

  piveau-hub-search:
    image: registry.gitlab.com/piveau/hub/piveau-hub-search:5.3.0
    container_name: piveau-hub-search
    logging:
      options:
        max-size: "50m"
    ports:
      - 8084:8080
      - 8086:8081
      - 5003:5000
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - OTEL_SDK_DISABLED=false
      - OTEL_SERVICE_NAME=piveau-hub-search
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
      - PIVEAU_FEATURE_FLAGS=${PIVEAU_FEATURE_FLAGS}
      - PIVEAU_PROFILE=${PIVEAU_PROFILE}
      - PIVEAU_HUB_SEARCH_API_KEY=${PIVEAU_HUB_SEARCH_API_KEY}
      - PIVEAU_HUB_SEARCH_CLI_CONFIG={"http":{},"telnet":{}}
      - PIVEAU_HUB_SEARCH_ES_CONFIG=${PIVEAU_HUB_SEARCH_ES_CONFIG}
      - PIVEAU_HUB_SEARCH_GAZETTEER_CONFIG={"url":"http://doesnotmatter.eu"}
      - JAVA_OPTS=-Xms1g -Xmx2g
    volumes:
      - ./piveau_profile:/piv-profile:ro

  piveau-hub-ui:
    image: registry.gitlab.com/piveau/hub/piveau-hub-ui:v1.16.6
    container_name: piveau-hub-ui
    logging:
      options:
        max-size: "50m"
    ports:
      - 8080:8080
    environment:
      - VITE_METADATA_TITLE=LINDASnext
      - VITE_API_BASE_URL=http://localhost:8084/
      - VITE_API_HUB_URL=http://localhost:8081/
      - VITE_AUTHENTICATION_KEYCLOAK_REALM=${VITE_AUTHENTICATION_KEYCLOAK_REALM}
      - VITE_AUTHENTICATION_KEYCLOAK_URL=${VITE_AUTHENTICATION_KEYCLOAK_URL}
      - VITE_AUTHENTICATION_KEYCLOAK_CLIENT_ID=${VITE_AUTHENTICATION_KEYCLOAK_CLIENT_ID}
      - VITE_ROUTING_ROUTER_OPTIONS_BASE=/

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.3
    container_name: elasticsearch
    logging:
      options:
        max-size: "50m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: curl -s -f http://elasticsearch:9200/_cat/health >/dev/null || exit 1
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2G -Xmx4G
    volumes:
      - ./volumes/elasticsearch-data:/usr/share/elasticsearch/data

  graphdb:
    image: ontotext/graphdb:10.8.8
    container_name: graphdb
    logging:
      options:
        max-size: "50m"
    ports:
      - 7200:7200
    command:
      - -Xms2g
      - -Xmx5g
      - -Ddefault.min.distinct.threshold=512m
    volumes:
      - ./volumes/graphdb-data:/opt/graphdb/dist/data

  graphdb-create-repo:
    image: curlimages/curl:latest
    container_name: graphdb-create-repo
    depends_on:
      graphdb:
        condition: service_started
    command:
      - /config/setup.sh
    volumes:
      - ./config/graphdb:/config:ro
    restart: "no"

  mitmproxy:
    image: mitmproxy/mitmproxy:12.1.1
    container_name: mitmproxy
    logging:
      options:
        max-size: "50m"
    ports:
      - 8888:8888
      - 8889:8889
    command:
      - mitmweb
      - --mode
      - reverse:http://graphdb:7200/
      - --listen-port
      - "8888"
      - --web-host
      - "0.0.0.0"
      - --web-port
      - "8889"
      - --set
      - web_password=mitm
      - -s
      - /scripts/strip_timeout.py
      - -s
      - /scripts/digest_to_basic.py
    volumes:
      - ./config/mitmproxy:/scripts

  #############################
  # docker-compose-consus.yml #
  #############################
  piveau-consus-importing-rdf:
    image: registry.gitlab.com/piveau/consus/piveau-consus-importing-rdf:1.10.1
    logging:
      options:
        max-size: "50m"
    environment:
      - OTEL_SDK_DISABLED=false
      - OTEL_SERVICE_NAME=piveau-consus-importing-rdf
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
      # - PIVEAU_PIPE_LOG_LEVEL=TRACE
      - JAVA_OPTS=-Xms200m -Xmx500m
    extra_hosts:
      - "host.docker.internal:host-gateway"

  piveau-consus-importing-ckan:
    image: registry.gitlab.com/piveau/consus/piveau-consus-importing-ckan:1.2.7
    logging:
      options:
        max-size: "50m"
    environment:
      - OTEL_SDK_DISABLED=false
      - OTEL_SERVICE_NAME=piveau-consus-importing-ckan
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
      - JAVA_OPTS=-Xms100m -Xmx200m

  piveau-consus-transforming-js:
    image: registry.gitlab.com/piveau/consus/piveau-consus-transforming-js:4.0.4
    logging:
      options:
        max-size: "50m"
    environment:
      - OTEL_SDK_DISABLED=false
      - OTEL_SERVICE_NAME=piveau-consus-transforming-js
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
      - JAVA_OPTS=-Xms200m -Xmx500m
    volumes:
      - ./piveau_scripts:/usr/verticles/scripts

  piveau-consus-exporting-hub:
    image: registry.gitlab.com/piveau/consus/piveau-consus-exporting-hub:6.0.5
    logging:
      options:
        max-size: "50m"
    environment:
      - OTEL_SDK_DISABLED=false
      - OTEL_SERVICE_NAME=piveau-consus-exporting-hub
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
      # - PIVEAU_PIPE_LOG_LEVEL=TRACE
      - JAVA_OPTS=-Xms200m -Xmx1g
      - PIVEAU_HUB_APIKEY=${PIVEAU_HUB_API_KEY}

  piveau-consus-scheduling:
    image: registry.gitlab.com/piveau/consus/piveau-consus-scheduling:4.1.0
    logging:
      options:
        max-size: "50m"
    ports:
      - "8090:8080"
      - "8095:8085"
      - "5001:5000" # Just make it also work for macOS
    environment:
      - OTEL_SDK_DISABLED=false
      - OTEL_SERVICE_NAME=piveau-consus-scheduling
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
      # - PIVEAU_PIPE_LOG_LEVEL=TRACE
      - JAVA_OPTS=-Xms100m -Xmx200m
      - PIVEAU_SHELL_CONFIG={"telnet":{},"http":{}}
    volumes:
      - ./piveau_pipes:/usr/verticles/pipes

  #################
  # OpenTelemetry #
  #################
  jaeger:
    image: docker.io/jaegertracing/all-in-one:1.75.0
    healthcheck:
      test: ["CMD-SHELL", "wget -nv -t1 --spider localhost:14269/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "16686:16686"
      - "4317:4317"

  collector:
    image: docker.io/otel/opentelemetry-collector-contrib:0.137.0
    command: >-
      --config=/collector.yaml
    depends_on:
      jaeger:
        condition: service_healthy
    volumes:
      - ./config/collector.yaml:/collector.yaml:ro

  prometheus:
    image: docker.io/prom/prometheus:v3.7.3
    command: >-
      --config.file=/prometheus.yaml
      --web.enable-lifecycle
    depends_on:
      - collector
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -nv -t1 --spider localhost:9090/-/healthy || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./config/prometheus.yaml:/prometheus.yaml:ro
    ports:
      - 9090:9090

  grafana:
    image: docker.io/grafana/grafana:12.3.0
    ports:
      - 3001:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
    volumes:
      - ./config/grafana.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -nv -t1 --spider localhost:3000/api/health || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  ####################
  # Custom services  #
  ####################
  piveau-consus-importing-csw:
    build: ../piveau_modules/piveau-consus-importing-csw
    logging:
      options:
        max-size: "50m"
    environment:
      - JAVA_OPTS=-Xms200m -Xmx500m
      #- PIVEAU_PIPE_LOG_LEVEL=TRACE
      - OTEL_SDK_DISABLED=true

  piveau-consus-patching:
    build: ../piveau_modules/piveau-consus-patching
    logging:
      options:
        max-size: "50m"
