apiVersion: apps/v1
kind: Deployment
metadata:
  name: piveau-ui
spec:
  template:
    spec:
      containers:
        - name: piveau-ui
          image: ghcr.io/opendata-swiss/ods-ui
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          env:
            - name: NUXT_PUBLIC_PIVEAU_HUB_SEARCH_URL
              valueFrom:
                configMapKeyRef:
                  name: public-endpoints
                  key: hub-search-endpoint
            - name: NUXT_PUBLIC_PIVEAU_HUB_REPO_URL
              valueFrom:
                configMapKeyRef:
                  name: public-endpoints
                  key: hub-repo-endpoint

            - name: NUXT_OAUTH_KEYCLOAK_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: auth-ui
                  key: server-url
            - name: NUXT_OAUTH_KEYCLOAK_REALM
              valueFrom:
                secretKeyRef:
                  name: auth-ui
                  key: realm
            - name: NUXT_OAUTH_KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth-ui
                  key: client-id
            - name: NUXT_OAUTH_KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-ui
                  key: client-secret
            - name: NUXT_SESSION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-ui
                  key: session-password

            - name: GITHUB_OWNER
              value: opendata-swiss
            - name: GITHUB_REPO
              value: metadata.swiss
            - name: GITHUB_BASE_BRANCH
              value: main
            - name: GITHUB_APP_ID
              valueFrom:
                secretKeyRef:
                  name: piveau-ui-github-app
                  key: app-id
            - name: GITHUB_APP_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: piveau-ui-github-app
                  key: private-key
            - name: GITHUB_APP_INSTALLATION_ID
              valueFrom:
                secretKeyRef:
                  name: piveau-ui-github-app
                  key: installation-id
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 1Gi
