name: Generate meta_harvester Files

on:
  push:
    branches:
      - '215-geoharvesters'
  workflow_dispatch:

jobs:
  generate-files:
    runs-on: ubuntu-latest

    # Set the working directory for all run commands in this job
    defaults:
      run:
        working-directory: ./opendata.swiss/metadata/meta_harvester

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: ./opendata.swiss/metadata/meta_harvester/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Activate venv
        run: eval $(poetry env activate)

      - name: Install dependencies
        working-directory: opendata.swiss/metadata/meta_harvester
        run: poetry install

      - name: List installed packages for debugging
        working-directory: opendata.swiss/metadata/meta_harvester
        run: poetry run pip list

      #- name: Run meta_harvester
      #  env:
      #    PIVEAU_HUB_API_KEY: ${{ secrets.PIVEAU_HUB_API_KEY }}
      #  working-directory: opendata.swiss/metadata/meta_harvester
      #  run: poetry run python -m meta_harvester generate

      # - name: Upload catalogues
      #   env:
      #     PIVEAU_HUB_API_KEY: ${{ secrets.PIVEAU_HUB_API_KEY }}
      #   working-directory: opendata.swiss/metadata/meta_harvester
      #   run: poetry run python -m meta_harvester create-catalogues

      - name: test with curl
        run: curl -i http://localhost:8081/catalogues

      - name: test with curl
        run: curl -i http://localhost:8090/runs

      - name: Run pipes
        run: poetry run python -m meta_harvester run-pipes
