name: Generate meta_harvester Files

on:
  push:
    branches:
      - 215-geoharvesters
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - "ACCEPTANCE"
          - "INT"
        default: "ACCEPTANCE"

jobs:
  workflow:
    runs-on: ubuntu-latest
    env:
      WORKFLOW_ENVIRONMENT: ${{ github.event.inputs.environment || 'ACCEPTANCE' }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Ensure no old .env file exists
        working-directory: ./opendata.swiss/metadata
        run: rm -f .env

      - name: Generate .env file (INT)
        if: env.WORKFLOW_ENVIRONMENT == 'INT'
        working-directory: ./opendata.swiss/metadata
        run: |
          echo "PIVEAU_HUB_API_KEY=${PIVEAU_HUB_API_KEY}" >> .env
          echo "HUB_REPO_ENDPOINT=${HUB_REPO_ENDPOINT}" >> .env
          echo "CONSUS_SCHEDULING_ENDPOINT=${CONSUS_SCHEDULING_ENDPOINT}" >> .env
          echo "CONSUS_SCHEDULING_USERNAME=${CONSUS_SCHEDULING_USERNAME}" >> .env
          echo "CONSUS_SCHEDULING_PASSWORD=${CONSUS_SCHEDULING_PASSWORD}" >> .env
        env:
          PIVEAU_HUB_API_KEY: ${{ secrets.PIVEAU_HUB_API_KEY_INT }}
          HUB_REPO_ENDPOINT: ${{ secrets.HUB_REPO_ENDPOINT_INT }}
          CONSUS_SCHEDULING_ENDPOINT: ${{ secrets.CONSUS_SCHEDULING_ENDPOINT_INT }}
          CONSUS_SCHEDULING_USERNAME: ${{ secrets.CONSUS_SCHEDULING_USERNAME_INT }}
          CONSUS_SCHEDULING_PASSWORD: ${{ secrets.CONSUS_SCHEDULING_PASSWORD_INT }}

      - name: Generate .env file (ACCEPTANCE)
        if: env.WORKFLOW_ENVIRONMENT == 'ACCEPTANCE'
        working-directory: ./opendata.swiss/metadata
        run: |
          echo "PIVEAU_HUB_API_KEY=${PIVEAU_HUB_API_KEY}" >> .env
          echo "HUB_REPO_ENDPOINT=${HUB_REPO_ENDPOINT}" >> .env
          echo "CONSUS_SCHEDULING_ENDPOINT=${CONSUS_SCHEDULING_ENDPOINT}" >> .env
          echo "CONSUS_SCHEDULING_USERNAME=${CONSUS_SCHEDULING_USERNAME}" >> .env
          echo "CONSUS_SCHEDULING_PASSWORD=${CONSUS_SCHEDULING_PASSWORD}" >> .env
        env:
          PIVEAU_HUB_API_KEY: ${{ secrets.PIVEAU_HUB_API_KEY_ACCEPTANCE }}
          HUB_REPO_ENDPOINT: ${{ secrets.HUB_REPO_ENDPOINT_ACCEPTANCE }}
          CONSUS_SCHEDULING_ENDPOINT: ${{ secrets.CONSUS_SCHEDULING_ENDPOINT_ACCEPTANCE }}
          CONSUS_SCHEDULING_USERNAME: ${{ secrets.CONSUS_SCHEDULING_USERNAME_ACCEPTANCE }}
          CONSUS_SCHEDULING_PASSWORD: ${{ secrets.CONSUS_SCHEDULING_PASSWORD_ACCEPTANCE }}


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: ./opendata.swiss/metadata/meta_harvester/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Activate venv
        working-directory: opendata.swiss/metadata/meta_harvester
        run: eval $(poetry env activate)

      - name: Install dependencies
        working-directory: opendata.swiss/metadata/meta_harvester
        run: poetry install

      - name: List installed packages for debugging
        working-directory: opendata.swiss/metadata/meta_harvester
        run: poetry run pip list

      - name: Run meta_harvester
        working-directory: opendata.swiss/metadata/meta_harvester
        run: poetry run python -m meta_harvester generate

      - name: List generated pipe files
        working-directory: opendata.swiss/metadata/meta_harvester
        run: |
          pwd
          ls -l ../piveau_pipes


      - name: Upload catalogues
        working-directory: opendata.swiss/metadata/meta_harvester
        # env:
        #   PIVEAU_HUB_API_KEY_ACCEPTANCE: ${{ secrets.PIVEAU_HUB_API_KEY_ACCEPTANCE }}
        #   HUB_REPO_ENDPOINT_ACCEPTANCE: ${{ secrets.HUB_REPO_ENDPOINT_ACCEPTANCE }}
        #   CONSUS_SCHEDULING_ENDPOINT_ACCEPTANCE: ${{ secrets.CONSUS_SCHEDULING_ENDPOINT_ACCEPTANCE }}
        #   CONSUS_SCHEDULING_USERNAME_ACCEPTANCE: ${{ secrets.CONSUS_SCHEDULING_USERNAME_ACCEPTANCE }}
        #   CONSUS_SCHEDULING_PASSWORD_ACCEPTANCE: ${{ secrets.CONSUS_SCHEDULING_PASSWORD_ACCEPTANCE }}
        run: poetry run python -m meta_harvester create-catalogues

      - name: Run pipes
        working-directory: opendata.swiss/metadata/meta_harvester
        # env:
        #   PIVEAU_HUB_API_KEY_ACCEPTANCE: ${{ secrets.PIVEAU_HUB_API_KEY_ACCEPTANCE }}
        #   HUB_REPO_ENDPOINT_ACCEPTANCE: ${{ secrets.HUB_REPO_ENDPOINT_ACCEPTANCE }}
        #   CONSUS_SCHEDULING_ENDPOINT_ACCEPTANCE: ${{ secrets.CONSUS_SCHEDULING_ENDPOINT_ACCEPTANCE }}
        #   CONSUS_SCHEDULING_USERNAME_ACCEPTANCE: ${{ secrets.CONSUS_SCHEDULING_USERNAME_ACCEPTANCE }}
        #   CONSUS_SCHEDULING_PASSWORD_ACCEPTANCE: ${{ secrets.CONSUS_SCHEDULING_PASSWORD_ACCEPTANCE }}
        run: poetry run python -m meta_harvester run-pipes
