name: Generate meta_harvester Files

on:
  push:
    branches:
      - '215-geoharvesters'
  workflow_dispatch:

jobs:
  generate-files:
    runs-on: ubuntu-latest

    # Set the working directory for all run commands in this job
    defaults:
      run:
        working-directory: ./opendata.swiss/metadata/meta_harvester

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: ./opendata.swiss/metadata/meta_harvester/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Activate venv
        run: poetry env activate

      - name: Install dependencies
        working-directory: opendata.swiss/metadata/meta_harvester
        run: |
          poetry install
          pip list

      - name: Check dependencies
        working-directory: opendata.swiss/metadata/meta_harvester
        run: pip list

      - name: Run meta_harvester
        working-directory: opendata.swiss/metadata/meta_harvester
        run: python -m meta_harvester generate

      - name: Run pipes
        run: python -m meta_harvester run-pipes
