name: "Script Trigger Workflow"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - "ACCEPTANCE"
          - "INT"
        default: "INT"

      action:
        description: "Action to perform"
        required: true
        type: choice
        options:
          - "HARVEST"
          - "HARVEST_SHOWCASES"
          - "CATALOGUES"
          - "DELETE_CATALOGUES"
          - "VOCABULARIES"
          - "DELETE_VOCABULARIES"
        default: "HARVEST"

jobs:
  workflow:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Ensure no old .env file exists
        working-directory: ./opendata.swiss/metadata
        run: rm -f .env

      - name: Generate .env file (INT)
        if: ${{ github.event.inputs.environment == 'INT' }}
        working-directory: ./opendata.swiss/metadata
        run: |
          echo "PIVEAU_HUB_API_KEY=${PIVEAU_HUB_API_KEY}" >> .env
          echo "HUB_REPO_ENDPOINT=${HUB_REPO_ENDPOINT}" >> .env
          echo "CONSUS_SCHEDULING_ENDPOINT=${CONSUS_SCHEDULING_ENDPOINT}" >> .env
          echo "CONSUS_SCHEDULING_USERNAME=${CONSUS_SCHEDULING_USERNAME}" >> .env
          echo "CONSUS_SCHEDULING_PASSWORD=${CONSUS_SCHEDULING_PASSWORD}" >> .env
        env:
          PIVEAU_HUB_API_KEY: ${{ secrets.PIVEAU_HUB_API_KEY_INT }}
          HUB_REPO_ENDPOINT: ${{ secrets.HUB_REPO_ENDPOINT_INT }}
          CONSUS_SCHEDULING_ENDPOINT: ${{ secrets.CONSUS_SCHEDULING_ENDPOINT_INT }}
          CONSUS_SCHEDULING_USERNAME: ${{ secrets.CONSUS_SCHEDULING_USERNAME_INT }}
          CONSUS_SCHEDULING_PASSWORD: ${{ secrets.CONSUS_SCHEDULING_PASSWORD_INT }}

      - name: Generate .env file (ACCEPTANCE)
        if: ${{ github.event.inputs.environment == 'ACCEPTANCE' }}
        working-directory: ./opendata.swiss/metadata
        run: |
          echo "PIVEAU_HUB_API_KEY=${PIVEAU_HUB_API_KEY}" >> .env
          echo "HUB_REPO_ENDPOINT=${HUB_REPO_ENDPOINT}" >> .env
          echo "CONSUS_SCHEDULING_ENDPOINT=${CONSUS_SCHEDULING_ENDPOINT}" >> .env
          echo "CONSUS_SCHEDULING_USERNAME=${CONSUS_SCHEDULING_USERNAME}" >> .env
          echo "CONSUS_SCHEDULING_PASSWORD=${CONSUS_SCHEDULING_PASSWORD}" >> .env
        env:
          PIVEAU_HUB_API_KEY: ${{ secrets.PIVEAU_HUB_API_KEY_ACCEPTANCE }}
          HUB_REPO_ENDPOINT: ${{ secrets.HUB_REPO_ENDPOINT_ACCEPTANCE }}
          CONSUS_SCHEDULING_ENDPOINT: ${{ secrets.CONSUS_SCHEDULING_ENDPOINT_ACCEPTANCE }}
          CONSUS_SCHEDULING_USERNAME: ${{ secrets.CONSUS_SCHEDULING_USERNAME_ACCEPTANCE }}
          CONSUS_SCHEDULING_PASSWORD: ${{ secrets.CONSUS_SCHEDULING_PASSWORD_ACCEPTANCE }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: ./opendata.swiss/metadata/meta_harvester/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Activate venv
        working-directory: opendata.swiss/metadata/meta_harvester
        run: eval $(poetry env activate)

      - name: Install dependencies
        working-directory: opendata.swiss/metadata/meta_harvester
        run: poetry install

      - name: Run the selected action
        working-directory: ./opendata.swiss/metadata
        run: |
          if [ "${{ github.event.inputs.action }}" == "HARVEST" ]; then
            cd meta_harvester;
            poetry run python -m meta_harvester generate;
            poetry run python -m meta_harvester create-catalogues;
            poetry run python -m meta_harvester run-pipes;
          elif [ "${{ github.event.inputs.action }}" == "HARVEST_SHOWCASES" ]; then
            poetry run python -m meta_harvester run-pipes static/pipe-showcases-ods;
          elif [ "${{ github.event.inputs.action }}" == "CATALOGUES" ]; then
            poetry run python -m meta_harvester create-catalogues;
          elif [ "${{ github.event.inputs.action }}" == "DELETE_CATALOGUES" ]; then
            poetry run python -m meta_harvester delete-catalogues;
          elif [ "${{ github.event.inputs.action }}" == "VOCABULARIES" ]; then
            ./scripts/vocabularies.sh;
          elif [ "${{ github.event.inputs.action }}" == "DELETE_VOCABULARIES" ]; then
            ./scripts/vocabularies_delete.sh;
          else
            echo "Unknown action: ${{ github.event.inputs.action }}";
            exit 1;
          fi
