name: "[UI] Tests"

on:
  push:
    paths:
      - "opendata.swiss/ui/**"
      - ".github/workflows/test-ui.yaml" # Trigger also if this workflow file is changed

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout branch
        uses: actions/checkout@v6
      - uses: fabasoad/setup-prolog-action@v1
      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
      - run: npm ci
        working-directory: opendata.swiss/ui
      - run: npm run lint
        working-directory: opendata.swiss/ui

  api-tests:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - uses: fabasoad/setup-prolog-action@v1

      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"

      - run: npm ci
        working-directory: opendata.swiss/ui

      - run: npm run dev &
        working-directory: opendata.swiss/ui
        env:
          NUXT_API_TUNER_TESTS: true

      - run: npx wait-on http://localhost:3000 -t 30s
        working-directory: opendata.swiss/ui

      - run: npm test -- --silent
        working-directory: opendata.swiss/ui
